name: mac-novnc

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-latest

    steps:
      - name: Enable VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate \
          -configure \
          -access -on \
          -clientopts -setvnclegacy -vnclegacy yes \
          -clientopts -setvncpw -vncpw "password" \
          -restart -agent     

      - name: Install noVNC
        run: |
          lsof -i :5900 || echo "no vnc server on 5900"
          git clone https://github.com/novnc/noVNC.git
          git clone https://github.com/novnc/websockify.git noVNC/utils/websockify

      - name: Start noVNC
        run: |
          cd noVNC
          nohup ./utils/novnc_proxy --vnc localhost:5900 --listen 6080 &

      - name: Install cloudflared
        run: brew install cloudflared

      - name: Expose web UI
        run: |
          cloudflared tunnel --url http://localhost:6080
